# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  [workflow_dispatch]
env: 
  A: 1
   
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone Action
        # You may pin to the exact commit or the version.
        # uses: sudosubin/git-clone-action@8a93ce24d47782e30077508cccacf8a05a891bae
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          # Repository owner and name. Ex: sudosubin/git-clone-action
          repository: ${{ github.repository }} # optional, default is ${{ github.repository }}
          # Git host platform. Ex: github, gitlab, bitbucket, gitee, or else (git.suckless.org, ...)
          platform: github # optional, default is github
          # Git branch or tag to checkout.
          ref: main # optional
          # Relative path from current directory, where to clone.
          path: ./ # optional
      - name: Show
        run: ls -la 
      - name: Public IP
        # uses: haythem/public-ip@80817b0f5a25abd023258727319a82edcce9bb83
        uses: haythem/public-ip@v1.2
        with:
          maxRetries: 5
      - name: NPM Target
      # You may pin to the exact commit or the version.
      # uses: anna-money/github-actions-npm@c39d5137ed17f1e97cc1fa24019708bd8c89fdb2
        uses: anna-money/github-actions-npm@v2
        with:
          # package.json target to run
          target: build # default is test
      - name: SCP deploy action
        # You may pin to the exact commit or the version.
        # uses: nogsantos/ssh-scp-deploy@48b9ca0b1adcb229b1568eebda8e16e06436495a
        uses: nogsantos/ssh-scp-deploy@v1.3.0
        with:
          # Sorce dir to deploy
          src: ./
          # SSH address
          host: data.ittps.ru
          # Remote dir path
          remote: /data/www/
          # SSH Port
          port: 22 # optional, default is 22
          # SSH User name
          user: root
          # Private key
          key: ${{ secrets.sshkey }}
          # Extra options for scp
#         options:  # optional
